//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesajlasma
    {
        public int MesajlasmaId { get; set; }
        public Nullable<int> MesajID { get; set; }
        public Nullable<int> GonderenKullaniciID { get; set; }
        public Nullable<int> AlanKullaniciID { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Kullanici Tbl_Kullanici1 { get; set; }
        public virtual Tbl_Mesaj Tbl_Mesaj { get; set; }
    }
}
