//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Favori
    {
        public int FavoriId { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Urun Tbl_Urun { get; set; }
    }
}
